### ISSUE TITLE
.css files use global layout by default, consider setting layout to null

### ISSUE THREAD

**Issue by justinfagnani** [jgarber623/eleventy-plugin-postcss#18]
I'm replacing a custom CSS extension with yours, on a site with a global default layout. I started getting errors because the layout was effecting .css files.

What I done in my CSS extension was to exclude .css files from layouts:

```ts
    getData: async function(inputPath) {
      return {
        layout: null,
      };
    },
```

This might be useful as an option. The workaround is to add an data file to the directory containing .css and set the layout to null, assuming that your styles are separated like that. Just excluding .css from layouts in the extension was very convenient though.

**Comment by jgarber623** [comment]
Thanks for filing this issue, @justinfagnani. I don't use globally-defined layouts like you describe which is why I never noticed the issue, _however_… it's a reasonable enough bug.

#20 fixes the issue and will be in an upcoming v1.0.0 release.

**Comment by jgarber623** [comment]
v1.0.0 is now available [on npm](https://www.npmjs.com/package/@jgarber/eleventy-plugin-postcss). Thanks again for reporting this issue!

**Comment by justinfagnani** [comment]
Thanks for the fast fix @jgarber623!
