### ISSUE TITLE
where are the output files?

### ISSUE THREAD

**Issue by Waoweens** [jgarber623/eleventy-plugin-postcss#21]
hi, i apologize if this is simple, i'm quite new to 11ty

this is my current setup:
```js
/** @param {import("@11ty/eleventy").UserConfig} eleventyConfig */
module.exports = function (eleventyConfig) {
	eleventyConfig.addPassthroughCopy({ 'src/_includes/styles': '/styles' });

	return {
		dir: {
			input: 'src',
		},
	};
};
```
there are CSS files in src/_include/styles

however now i want some PostCSS stuff:
```js
module.exports = {
	map: 'inline',
	plugins: [
		require('tailwindcss'),
		require('autoprefixer'),
	]
}
```
so i replaced it with the plugin
```diff
- eleventyConfig.addPassthroughCopy({ 'src/_includes/styles': '/styles' });
+ eleventyConfig.addPlugin(require('@jgarber/eleventy-plugin-postcss'));
```
but if i run build, i don't see any css files in the output directory. am i missing something?

**Comment by Waoweens** [comment]
ok so looks like the plugin does not compile files inside _include, if i move my css files somewhere else it works

**Comment by jgarber623** [comment]
@Waoweens Hello! Thanks for giving this plugin a try. I think you've come to a proper resolution, but let me share a few thoughts based on your approach:

1. eleventy-plugin-postcss (in its default configuration) will transform Eleventy templates in the configured `src` path for files with the extensions `css`, `pcss`, and `postcss`.

2. The configured `includes` folder (`./src/_includes` in your case) in the configured `src` path is _not_ considered when Eleventy searches your project for templates. The [Working with Templates](https://www.11ty.dev/docs/templates/) documentation doesn't obviously say so, though, but [`Eleventy.js` in v2.0.1](https://github.com/11ty/eleventy/blob/v2.0.1/src/Eleventy.js#L838-L847) has some very specific-looking code related to ignoring CSS files in the configured `includes` folder. v3.0.0 (currently in alpha) is _quite_ different, but as best as I can tell behaves similarly ([see the `isTemplateFile` function in `ProjectDirectories.js](https://github.com/11ty/eleventy/blob/main/src/Util/ProjectDirectories.js#L247-L258)). Assuming those two pieces of linked code are relevant, the takeaway is "Files in the configured `includes` folder _are not_ considered templates."

You can test that theory by adding a file, `./src/_includes/index.liquid`, and rebuilding your site:

```liquid
Hello, world!
```

If that's the only file in your `src` path, the `_site` folder may not be created at all. I see output like:

```
> eleventy-passthrough-test@0.1.0 build
> eleventy --quiet

[11ty] Wrote 0 files in 0.01 seconds (v2.0.1)
```

3. Using [Passthrough File Copy](https://www.11ty.dev/docs/copy/) is strictly an instruction to as-is copy one or more files from one path in your project to another path in the output directory. Eleventy doesn't treat these as templates, either. The [Adding CSS, JS, Fonts](https://www.11ty.dev/docs/assets/) documentation _does_ include an example using Passthrough File Copy, but I believe the assumption there is that's a "normal" CSS file.

> is there a way to configure where files are outputted?

Yes! Sort of.

The easiest way to use eleventy-plugin-postcss is to place your input CSS files in a file path similar to where the output will be. So, I have a file at `./src/assets/stylesheets/styles.css` that PostCSS processes via this plugin and generates an output file at `./_site/assets/stylesheets/styles.css`. That's the simplest and most sensible approach _to me_ and is how I organize my projects.

_However_. Eleventy supports template format chaining, so you could achieve what you'd like on a per-file basis by using another template language (like Liquid) with a file named `./src/some/arbitrary/file/path/styles.css.liquid`:

```liquid
---
permalink: "/styles/screen.css"
---

html {
  background: blue;
}
```

To my eye, that's a bit clunky, but it seems it's possible. I don't intend to add configuration to this plugin to support configurable output paths. If that's a critical feature for your project, you may want to see if [a different community-built plugin](https://www.11ty.dev/docs/plugins/community/) supports that feature.

> [!NOTE]
> I've done my best to come to reasonable conclusions based on what I could find in Eleventy's documentation and source code. Apologies if you find something that contradicts those conclusions! Let me know if you do, of course.

**Comment by Waoweens** [comment]
hi! sorry for my late response, i've not been in a good state this week

thank you for your insight on that behavior of `_include`. that feels like something that should be documented

i have solved my issue by moving everything that's not actual includes outside of `_include` and just being a bit more smart about directory placement

thank you for the plugin! i like the simplicity of it

i think i can close this now
